//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEIDGApi
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CEIDGApi.IDataStoreProvider")]
    public interface IDataStoreProvider
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataStoreProvider/DoWork", ReplyAction="http://tempuri.org/IDataStoreProvider/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataStoreProvider/GetData", ReplyAction="http://tempuri.org/IDataStoreProvider/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(
                    string AuthToken, 
                    System.Collections.Generic.List<string> NIP, 
                    System.Collections.Generic.List<string> REGON, 
                    System.Collections.Generic.List<string> NIP_SC, 
                    System.Collections.Generic.List<string> REGON_SC, 
                    System.Collections.Generic.List<string> Name, 
                    System.Collections.Generic.List<string> Province, 
                    System.Collections.Generic.List<string> County, 
                    System.Collections.Generic.List<string> Commune, 
                    System.Collections.Generic.List<string> City, 
                    System.Collections.Generic.List<string> Street, 
                    System.Collections.Generic.List<string> Postcode, 
                    System.Nullable<System.DateTime> DateFrom, 
                    System.Nullable<System.DateTime> DateTo, 
                    System.Collections.Generic.List<string> PKD, 
                    System.Collections.Generic.List<int> status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataStoreProvider/GetMigrationData", ReplyAction="http://tempuri.org/IDataStoreProvider/GetMigrationDataResponse")]
        System.Threading.Tasks.Task<string> GetMigrationDataAsync(
                    string AuthToken, 
                    System.Collections.Generic.List<string> NIP, 
                    System.Collections.Generic.List<string> REGON, 
                    System.Collections.Generic.List<string> NIP_SC, 
                    System.Collections.Generic.List<string> REGON_SC, 
                    System.Collections.Generic.List<string> Name, 
                    System.Collections.Generic.List<string> Province, 
                    System.Collections.Generic.List<string> County, 
                    System.Collections.Generic.List<string> Commune, 
                    System.Collections.Generic.List<string> City, 
                    System.Collections.Generic.List<string> Street, 
                    System.Collections.Generic.List<string> Postcode, 
                    System.Nullable<System.DateTime> DateFrom, 
                    System.Nullable<System.DateTime> DateTo, 
                    System.Collections.Generic.List<string> PKD, 
                    System.Collections.Generic.List<int> status, 
                    System.Nullable<System.DateTime> MigrationDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataStoreProvider/GetMigrationDataNewFormat", ReplyAction="http://tempuri.org/IDataStoreProvider/GetMigrationDataNewFormatResponse")]
        System.Threading.Tasks.Task<string> GetMigrationDataNewFormatAsync(
                    string AuthToken, 
                    System.Collections.Generic.List<string> NIP, 
                    System.Collections.Generic.List<string> REGON, 
                    System.Collections.Generic.List<string> NIP_SC, 
                    System.Collections.Generic.List<string> REGON_SC, 
                    System.Collections.Generic.List<string> Name, 
                    System.Collections.Generic.List<string> Province, 
                    System.Collections.Generic.List<string> County, 
                    System.Collections.Generic.List<string> Commune, 
                    System.Collections.Generic.List<string> City, 
                    System.Collections.Generic.List<string> Street, 
                    System.Collections.Generic.List<string> Postcode, 
                    System.Nullable<System.DateTime> DateFrom, 
                    System.Nullable<System.DateTime> DateTo, 
                    System.Collections.Generic.List<string> PKD, 
                    System.Collections.Generic.List<int> status, 
                    System.Nullable<System.DateTime> MigrationDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataStoreProvider/GetMigrationDataUniqueId", ReplyAction="http://tempuri.org/IDataStoreProvider/GetMigrationDataUniqueIdResponse")]
        System.Threading.Tasks.Task<string> GetMigrationDataUniqueIdAsync(
                    string AuthToken, 
                    System.Collections.Generic.List<string> NIP, 
                    System.Collections.Generic.List<string> REGON, 
                    System.Collections.Generic.List<string> NIP_SC, 
                    System.Collections.Generic.List<string> REGON_SC, 
                    System.Collections.Generic.List<string> Name, 
                    System.Collections.Generic.List<string> Province, 
                    System.Collections.Generic.List<string> County, 
                    System.Collections.Generic.List<string> Commune, 
                    System.Collections.Generic.List<string> City, 
                    System.Collections.Generic.List<string> Street, 
                    System.Collections.Generic.List<string> Postcode, 
                    System.Nullable<System.DateTime> DateFrom, 
                    System.Nullable<System.DateTime> DateTo, 
                    System.Collections.Generic.List<string> PKD, 
                    System.Collections.Generic.List<int> status, 
                    System.Collections.Generic.List<string> UniqueId, 
                    System.Nullable<System.DateTime> MigrationDateFrom, 
                    System.Nullable<System.DateTime> MigrationDateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataStoreProvider/GetID", ReplyAction="http://tempuri.org/IDataStoreProvider/GetIDResponse")]
        System.Threading.Tasks.Task<string> GetIDAsync(string AuthToken, System.Nullable<System.DateTime> DateFrom, System.Nullable<System.DateTime> DateTo, System.Nullable<System.DateTime> MigrationDateFrom, System.Nullable<System.DateTime> MigrationDateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataStoreProvider/GetMigrationDataExtendedInfo", ReplyAction="http://tempuri.org/IDataStoreProvider/GetMigrationDataExtendedInfoResponse")]
        System.Threading.Tasks.Task<string> GetMigrationDataExtendedInfoAsync(
                    string AuthToken, 
                    System.Collections.Generic.List<string> NIP, 
                    System.Collections.Generic.List<string> REGON, 
                    System.Collections.Generic.List<string> NIP_SC, 
                    System.Collections.Generic.List<string> REGON_SC, 
                    System.Collections.Generic.List<string> Name, 
                    System.Collections.Generic.List<string> Province, 
                    System.Collections.Generic.List<string> County, 
                    System.Collections.Generic.List<string> Commune, 
                    System.Collections.Generic.List<string> City, 
                    System.Collections.Generic.List<string> Street, 
                    System.Collections.Generic.List<string> Postcode, 
                    System.Nullable<System.DateTime> DateFrom, 
                    System.Nullable<System.DateTime> DateTo, 
                    System.Collections.Generic.List<string> PKD, 
                    System.Collections.Generic.List<int> status, 
                    System.Collections.Generic.List<string> UniqueId, 
                    System.Nullable<System.DateTime> MigrationDateFrom, 
                    System.Nullable<System.DateTime> MigrationDateTo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    public interface IDataStoreProviderChannel : CEIDGApi.IDataStoreProvider, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    public partial class DataStoreProviderClient : System.ServiceModel.ClientBase<CEIDGApi.IDataStoreProvider>, CEIDGApi.IDataStoreProvider
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DataStoreProviderClient(EndpointConfiguration endpointConfiguration) : 
                base(DataStoreProviderClient.GetBindingForEndpoint(endpointConfiguration), DataStoreProviderClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataStoreProviderClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DataStoreProviderClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataStoreProviderClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DataStoreProviderClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataStoreProviderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task DoWorkAsync()
        {
            return base.Channel.DoWorkAsync();
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(
                    string AuthToken, 
                    System.Collections.Generic.List<string> NIP, 
                    System.Collections.Generic.List<string> REGON, 
                    System.Collections.Generic.List<string> NIP_SC, 
                    System.Collections.Generic.List<string> REGON_SC, 
                    System.Collections.Generic.List<string> Name, 
                    System.Collections.Generic.List<string> Province, 
                    System.Collections.Generic.List<string> County, 
                    System.Collections.Generic.List<string> Commune, 
                    System.Collections.Generic.List<string> City, 
                    System.Collections.Generic.List<string> Street, 
                    System.Collections.Generic.List<string> Postcode, 
                    System.Nullable<System.DateTime> DateFrom, 
                    System.Nullable<System.DateTime> DateTo, 
                    System.Collections.Generic.List<string> PKD, 
                    System.Collections.Generic.List<int> status)
        {
            return base.Channel.GetDataAsync(AuthToken, NIP, REGON, NIP_SC, REGON_SC, Name, Province, County, Commune, City, Street, Postcode, DateFrom, DateTo, PKD, status);
        }
        
        public System.Threading.Tasks.Task<string> GetMigrationDataAsync(
                    string AuthToken, 
                    System.Collections.Generic.List<string> NIP, 
                    System.Collections.Generic.List<string> REGON, 
                    System.Collections.Generic.List<string> NIP_SC, 
                    System.Collections.Generic.List<string> REGON_SC, 
                    System.Collections.Generic.List<string> Name, 
                    System.Collections.Generic.List<string> Province, 
                    System.Collections.Generic.List<string> County, 
                    System.Collections.Generic.List<string> Commune, 
                    System.Collections.Generic.List<string> City, 
                    System.Collections.Generic.List<string> Street, 
                    System.Collections.Generic.List<string> Postcode, 
                    System.Nullable<System.DateTime> DateFrom, 
                    System.Nullable<System.DateTime> DateTo, 
                    System.Collections.Generic.List<string> PKD, 
                    System.Collections.Generic.List<int> status, 
                    System.Nullable<System.DateTime> MigrationDate)
        {
            return base.Channel.GetMigrationDataAsync(AuthToken, NIP, REGON, NIP_SC, REGON_SC, Name, Province, County, Commune, City, Street, Postcode, DateFrom, DateTo, PKD, status, MigrationDate);
        }
        
        public System.Threading.Tasks.Task<string> GetMigrationDataNewFormatAsync(
                    string AuthToken, 
                    System.Collections.Generic.List<string> NIP, 
                    System.Collections.Generic.List<string> REGON, 
                    System.Collections.Generic.List<string> NIP_SC, 
                    System.Collections.Generic.List<string> REGON_SC, 
                    System.Collections.Generic.List<string> Name, 
                    System.Collections.Generic.List<string> Province, 
                    System.Collections.Generic.List<string> County, 
                    System.Collections.Generic.List<string> Commune, 
                    System.Collections.Generic.List<string> City, 
                    System.Collections.Generic.List<string> Street, 
                    System.Collections.Generic.List<string> Postcode, 
                    System.Nullable<System.DateTime> DateFrom, 
                    System.Nullable<System.DateTime> DateTo, 
                    System.Collections.Generic.List<string> PKD, 
                    System.Collections.Generic.List<int> status, 
                    System.Nullable<System.DateTime> MigrationDate)
        {
            return base.Channel.GetMigrationDataNewFormatAsync(AuthToken, NIP, REGON, NIP_SC, REGON_SC, Name, Province, County, Commune, City, Street, Postcode, DateFrom, DateTo, PKD, status, MigrationDate);
        }
        
        public System.Threading.Tasks.Task<string> GetMigrationDataUniqueIdAsync(
                    string AuthToken, 
                    System.Collections.Generic.List<string> NIP, 
                    System.Collections.Generic.List<string> REGON, 
                    System.Collections.Generic.List<string> NIP_SC, 
                    System.Collections.Generic.List<string> REGON_SC, 
                    System.Collections.Generic.List<string> Name, 
                    System.Collections.Generic.List<string> Province, 
                    System.Collections.Generic.List<string> County, 
                    System.Collections.Generic.List<string> Commune, 
                    System.Collections.Generic.List<string> City, 
                    System.Collections.Generic.List<string> Street, 
                    System.Collections.Generic.List<string> Postcode, 
                    System.Nullable<System.DateTime> DateFrom, 
                    System.Nullable<System.DateTime> DateTo, 
                    System.Collections.Generic.List<string> PKD, 
                    System.Collections.Generic.List<int> status, 
                    System.Collections.Generic.List<string> UniqueId, 
                    System.Nullable<System.DateTime> MigrationDateFrom, 
                    System.Nullable<System.DateTime> MigrationDateTo)
        {
            return base.Channel.GetMigrationDataUniqueIdAsync(AuthToken, NIP, REGON, NIP_SC, REGON_SC, Name, Province, County, Commune, City, Street, Postcode, DateFrom, DateTo, PKD, status, UniqueId, MigrationDateFrom, MigrationDateTo);
        }
        
        public System.Threading.Tasks.Task<string> GetIDAsync(string AuthToken, System.Nullable<System.DateTime> DateFrom, System.Nullable<System.DateTime> DateTo, System.Nullable<System.DateTime> MigrationDateFrom, System.Nullable<System.DateTime> MigrationDateTo)
        {
            return base.Channel.GetIDAsync(AuthToken, DateFrom, DateTo, MigrationDateFrom, MigrationDateTo);
        }
        
        public System.Threading.Tasks.Task<string> GetMigrationDataExtendedInfoAsync(
                    string AuthToken, 
                    System.Collections.Generic.List<string> NIP, 
                    System.Collections.Generic.List<string> REGON, 
                    System.Collections.Generic.List<string> NIP_SC, 
                    System.Collections.Generic.List<string> REGON_SC, 
                    System.Collections.Generic.List<string> Name, 
                    System.Collections.Generic.List<string> Province, 
                    System.Collections.Generic.List<string> County, 
                    System.Collections.Generic.List<string> Commune, 
                    System.Collections.Generic.List<string> City, 
                    System.Collections.Generic.List<string> Street, 
                    System.Collections.Generic.List<string> Postcode, 
                    System.Nullable<System.DateTime> DateFrom, 
                    System.Nullable<System.DateTime> DateTo, 
                    System.Collections.Generic.List<string> PKD, 
                    System.Collections.Generic.List<int> status, 
                    System.Collections.Generic.List<string> UniqueId, 
                    System.Nullable<System.DateTime> MigrationDateFrom, 
                    System.Nullable<System.DateTime> MigrationDateTo)
        {
            return base.Channel.GetMigrationDataExtendedInfoAsync(AuthToken, NIP, REGON, NIP_SC, REGON_SC, Name, Province, County, Commune, City, Street, Postcode, DateFrom, DateTo, PKD, status, UniqueId, MigrationDateFrom, MigrationDateTo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IDataStoreProvider))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IDataStoreProvider1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IDataStoreProvider))
            {
                return new System.ServiceModel.EndpointAddress("http://datastore.ceidg.gov.pl/CEIDG.DataStore/services/DataStoreProvider.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IDataStoreProvider1))
            {
                return new System.ServiceModel.EndpointAddress("https://datastore.ceidg.gov.pl/CEIDG.DataStore/services/DataStoreProvider.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IDataStoreProvider,
            
            BasicHttpBinding_IDataStoreProvider1,
        }
    }
}
